require 'rake/clean'

def sample_directories
  FileList['*'].exclude('common').exclude('resource').exclude do |e|
    !File.directory?(e)
  end
end

task :setup do
  f = sample_directories
  f.each do |dir|
    cd dir do
      ['CMakeLists.txt', 'Rakefile'].each do |src|
        FileUtils.ln_s("../common/#{src}", src, **{ verbose: true })
      end
    end
  end
end



namespace :generate do
  desc 'generate .ani resources for samples'
  task :resource do
    f = sample_directories
    aseprites = FileList['resource/*.aseprite']
    f.pathmap('%n/Source/ani').each do |dir|
      aseprites.each do |ase|
        ani = ase.pathmap("#{dir}/%n.ani")
        sh "../aseprite_extension/batch_export.sh #{ase} #{ani}"
      end
    end
  end
end
